### PR TITLE
Fix galaxy scrapers?

### PR DESCRIPTION
**Pull request by hexylena**
Not sure if this is useful given the pending transition to bioschemas but maybe it makes them functional again in the meantime. We joined TeSS club a year ago with the hope of getting the GTN content indexed again and if there's no precise timeline on bioschemas scrapers (and there's so much work to do!) maybe it makes sense to do something like this in the interim?

I did some print debugging and I'm not sure all the right attributes are getting pulled out by github.com/ElixirTeSS/TeSS_RDF_Extractors but not sure how to fix that.

Here's some snippets from the logs:

[Running Galaxy Training network JSONLD scraper]
Scraping...
https://training.galaxyproject.org/training-material/topics/metabolomics/tutorials/lcms-preprocessing/slides.html

<details>
<summary>JSON Output</summary>

```json
{
  "@context": "http://schema.org",
  "@type": "Course",
  "accessMode": [
    "textual",
    "visual"
  ],
  "accessModeSufficient": [
    "textual",
    "visual"
  ],
  "accessibilityControl": [
    "fullKeyboardControl",
    "fullMouseControl"
  ],
  "accessibilityFeature": [
    "alternativeText",
    "tableOfContents"
  ],
  "accessibilitySummary": "Short descriptions are present but long descriptions will be needed for non-visual users",
  "audience": {
    "@type": "EducationalAudience",
    "educationalRole": "students"
  },
  "citation": {
    "@type": "CreativeWork",
    "name": "Community-Driven Data Analysis Training for Biology",
    "url": "https://doi.org/10.1016/j.cels.2018.05.012"
  },
  "copyrightHolder": {
    "@type": "Organization",
    "email": "galaxytrainingnetwork@gmail.com",
    "name": "Galaxy Training Network",
    "url": "https://galaxyproject.org/teach/gtn/"
  },
  "dateModified": "1970-01-01 00:33:41 +0000",
  "discussionUrl": "https://gitter.im/Galaxy-Training-Network/Lobby",
  "headline": "Mass spectrometry: LC-MS preprocessing - advanced",
  "interactivityType": "mixed",
  "isAccessibleForFree": true,
  "isFamilyFriendly": true,
  "license": "https://spdx.org/licenses/CC-BY-4.0.html",
  "producer": {
    "@type": "Organization",
    "email": "galaxytrainingnetwork@gmail.com",
    "name": "Galaxy Training Network",
    "url": "https://galaxyproject.org/teach/gtn/"
  },
  "provider": {
    "@type": "Organization",
    "email": "galaxytrainingnetwork@gmail.com",
    "name": "Galaxy Training Network",
    "url": "https://galaxyproject.org/teach/gtn/"
  },
  "sourceOrganization": {
    "@type": "Organization",
    "email": "galaxytrainingnetwork@gmail.com",
    "name": "Galaxy Training Network",
    "url": "https://galaxyproject.org/teach/gtn/"
  },
  "isPartOf": {
    "@type": "CreativeWork",
    "name": "Metabolomics",
    "description": "Training material to analyse Mass spectrometry data in Galaxy: Metabolomics (LCMS, FIAMS, GCMS, NMR) and imaging.",
    "url": "https://training.galaxyproject.org//training-material/topics/metabolomics/"
  },
  "courseCode": "metabolomics / lcms-preprocessing / slides",
  "learningResourceType": "slides",
  "name": "Slides for 'Mass spectrometry: LC-MS preprocessing - advanced' tutorial",
  "url": "https://training.galaxyproject.org//training-material/topics/metabolomics/tutorials/lcms-preprocessing/slides.html",
  "description": "",
  "inLanguage": {
    "@type": "Language",
    "name": "English",
    "alternateName": "en"
  },
  "coursePrerequisites": [
    {
      "@type": "CreativeWork",
      "url": "https://training.galaxyproject.org//training-material/topics/introduction/",
      "name": "Introduction to Galaxy Analyses",
      "description": "Introduction to Galaxy Analyses",
      "provider": {
        "@type": "Organization",
        "email": "galaxytrainingnetwork@gmail.com",
        "name": "Galaxy Training Network",
        "url": "https://galaxyproject.org/teach/gtn/"
      }
    }
  ],
  "hasPart": [

  ],
  "author": [
    {
      "@type": "Person",
      "name": "Jean-François Martin"
    },
    {
      "@type": "Person",
      "name": "Mélanie Petera"
    }
  ],
  "contributor": [
    {
      "@type": "Person",
      "name": "Jean-François Martin"
    },
    {
      "@type": "Person",
      "name": "Mélanie Petera"
    }
  ],
  "about": [
    {
      "@type": "CreativeWork",
      "name": "Metabolomics",
      "description": "Training material to analyse Mass spectrometry data in Galaxy: Metabolomics (LCMS, FIAMS, GCMS, NMR) and imaging.",
      "url": "https://training.galaxyproject.org//training-material/topics/metabolomics/"
    },
    {
      "@type": "DefinedTerm",
      "@id": "http://edamontology.org/topic_3172",
      "inDefinedTermSet": "http://edamontology.org",
      "termCode": "topic_3172",
      "url": "https://bioportal.bioontology.org/ontologies/EDAM/?p=classes&conceptid=http%3A%2F%2Fedamontology.org%2Ftopic_3172"
    }
  ]
}
```

</details>

And I've printed out the materials it's produced as well

<details>
<summary>Output Ruby Objects</summary>
```
Pre-loading schema.org context...
#<Tess::API::Material:0x000055e38529add8
 @authors=[],
 @content_provider=
  #<Tess::API::ContentProvider:0x000055e3827ead18
   @content_provider_type="Project",
   @description=
    "Collection of tutorials developed and maintained by the worldwide Galaxy community ",
   @image_url=
    "https://raw.githubusercontent.com/galaxyproject/training-material/master/shared/images/GTNLogo1000.png",
   @node_name=nil,
   @title="Galaxy Training",
   @url="https://training.galaxyproject.org/training-material/sitemap.xml">,
 @contributors=[],
 @external_resources_attributes=[],
 @keywords=[],
 @last_scraped=2021-11-25 09:50:59 +0100,
 @node_ids=[],
 @operation_names=[],
 @package_ids=[],
 @scientific_topic_names=[],
 @scraper_record=true,
 @target_audience=[],
 @title="Community-Driven Data Analysis Training for Biology",
 @url="https://doi.org/10.1016/j.cels.2018.05.012">
#<Tess::API::Material:0x000055e383f5e670
 @authors=[],
 @content_provider=
  #<Tess::API::ContentProvider:0x000055e3827ead18
   @content_provider_type="Project",
   @description=
    "Collection of tutorials developed and maintained by the worldwide Galaxy community ",
   @image_url=
    "https://raw.githubusercontent.com/galaxyproject/training-material/master/shared/images/GTNLogo1000.png",
   @node_name=nil,
   @title="Galaxy Training",
   @url="https://training.galaxyproject.org/training-material/sitemap.xml">,
 @contributors=[],
 @external_resources_attributes=[],
 @keywords=[],
 @last_scraped=2021-11-25 09:50:59 +0100,
 @node_ids=[],
 @operation_names=[],
 @package_ids=[],
 @scientific_topic_names=[],
 @scraper_record=true,
 @short_description="Introduction to Galaxy Analyses",
 @target_audience=[],
 @title="Introduction to Galaxy Analyses",
 @url=
  "https://training.galaxyproject.org//training-material/topics/introduction/">
#<Tess::API::Material:0x000055e3852bd6a8
 @authors=[],
 @content_provider=
  #<Tess::API::ContentProvider:0x000055e3827ead18
   @content_provider_type="Project",
   @description=
    "Collection of tutorials developed and maintained by the worldwide Galaxy community ",
   @image_url=
    "https://raw.githubusercontent.com/galaxyproject/training-material/master/shared/images/GTNLogo1000.png",
   @node_name=nil,
   @title="Galaxy Training",
   @url="https://training.galaxyproject.org/training-material/sitemap.xml">,
 @contributors=[],
 @external_resources_attributes=[],
 @keywords=[],
 @last_scraped=2021-11-25 09:50:59 +0100,
 @node_ids=[],
 @operation_names=[],
 @package_ids=[],
 @scientific_topic_names=[],
 @scraper_record=true,
 @short_description=
  "Training material to analyse Mass spectrometry data in Galaxy: Metabolomics (LCMS, FIAMS, GCMS, NMR) and imaging.",
 @target_audience=[],
 @title="Metabolomics",
 @url=
  "https://training.galaxyproject.org//training-material/topics/metabolomics/">
#<Tess::API::Material:0x000055e3852d37c8
 @authors=[],
 @content_provider=
  #<Tess::API::ContentProvider:0x000055e3827ead18
   @content_provider_type="Project",
   @description=
    "Collection of tutorials developed and maintained by the worldwide Galaxy community ",
   @image_url=
    "https://raw.githubusercontent.com/galaxyproject/training-material/master/shared/images/GTNLogo1000.png",
   @node_name=nil,
   @title="Galaxy Training",
   @url="https://training.galaxyproject.org/training-material/sitemap.xml">,
 @contributors=[],
 @external_resources_attributes=[],
 @keywords=[],
 @last_scraped=2021-11-25 09:50:59 +0100,
 @node_ids=[],
 @operation_names=[],
 @package_ids=[],
 @scientific_topic_names=[],
 @scraper_record=true,
 @short_description=
  "Training material to analyse Mass spectrometry data in Galaxy: Metabolomics (LCMS, FIAMS, GCMS, NMR) and imaging.",
 @target_audience=[],
 @title="Metabolomics",
 @url=
  "https://training.galaxyproject.org//training-material/topics/metabolomics/">
```
</details>

And you'll notice ok, it produces 4 Tess materials from that, and none of them seem to be properly about the source json-ld. It's found `https://doi.org/10.1016/j.cels.2018.05.012`, `https://training.galaxyproject.org//training-material/topics/metabolomics/` twice over, and then the introduction topic once. The json-ld all validates successfully against https://validator.schema.org/

Anyway I guess all this goes to say if there's any WIP on the bioschemas based validator I'd love to give it a whirl.

### CODE REVIEW

**Comment by fbacall** [comment]
Hi Helena. Sorry this PR was ignored :(

It looks like all the changes you made were sensible.

Just a quick question, is it still the case that the GTN sitemap could be filtered using the regex: `(slides|tutorial).html$` to avoid fetching pages without any markup?

**Comment by hexylena** [comment]
No worries @fbacall. Yes we could filter that using that regex, that can make sense

**Comment by fbacall** [comment]
Just FYI we're now scraping `LearningResource`-marked up pages from the GTN sitemap: https://tess.elixir-europe.org/materials?content_provider=Galaxy+Training

**Comment by hexylena** [comment]
That's fantastic news, thanks @fbacall !! We've been waiting for this moment for 3 years, very exciting for us.

**Pull request closed without merging**
